name: Secret Scanning

on:
  push:
    branches: [ main, '**' ]
  pull_request:

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    name: Scan repository for secrets using Gitleaks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run gitleaks scan
        uses: zricethezav/gitleaks-action@v2
        with:
          args: --path=. --verbose --no-git
